on:
  push:
    branches:
      - master

jobs:
  export_game:
    runs-on: ubuntu-latest
    name: Export game to Github
    steps:
      - name: checkout
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0
      - name: create game release
        uses: firebelley/godot-export@v5.1.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.0.3/Godot_v4.0.3-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.0.3/Godot_v4.0.3-stable_export_templates.tpz
          relative_project_path: ./godot
        env:
          GITHUB_TOKEN: ${{ secrets.GH_CREDENTIALS }}
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: download HTML5
        uses: dsaltares/fetch-gh-release-asset@master
        with:
            version: "latest"
            file: HTML5.zip
            token: "${{ secrets.GH_CREDENTIALS }}"
      - name: deploy to itch.io (HTML5)
        uses: manleydev/butler-publish-itchio-action@master
        env:
            BUTLER_CREDENTIALS: ${{ secrets.ITCH_API_KEY }}
            CHANNEL: html
            ITCH_GAME: template
            ITCH_USER: houst
            PACKAGE: HTML5.zip
            VERSION: ${{ steps.download-html.outputs.version }}
